#!/usr/bin/env python3
"""Run gseapy ssGSEA on ER-positive TCGA BRCA expression data.

The script reads the filtered TCGA expression matrix generated by
filter_tcga_er_positive.py and an ARCHS4 kinase co-expression signature table.
It writes both gseapy's long-format report and an explicit wide NES matrix
(samples x kinase signatures) for downstream correlation analysis.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import gseapy as gp
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=Path("/path/to/TCGA_data"),
        help="Directory containing TCGA input files and outputs.",
    )
    parser.add_argument("--expression-file", type=Path, default=None)
    parser.add_argument("--signature-file", type=Path, default=None)
    parser.add_argument("--out-dir", type=Path, default=None)
    parser.add_argument(
        "--min-size",
        type=int,
        default=1,
        help="Minimum gene-set size passed to gseapy.ssgsea.",
    )
    parser.add_argument(
        "--max-size",
        type=int,
        default=100000,
        help="Maximum gene-set size passed to gseapy.ssgsea.",
    )
    return parser.parse_args()


def load_signatures(signature_file: Path) -> dict[str, list[str]]:
    signature_df = pd.read_csv(signature_file, sep="\t", header=None)
    signatures: dict[str, list[str]] = {}
    for _, row in signature_df.iterrows():
        signature_name = str(row.iloc[0]).strip()
        genes = [
            str(g).strip()
            for g in row.iloc[1:].dropna().tolist()
            if str(g).strip() not in {"", "NA", "nan"}
        ]
        if signature_name and genes:
            signatures[signature_name] = genes
    if not signatures:
        raise ValueError(f"No signatures were parsed from {signature_file}")
    return signatures


def main() -> None:
    args = parse_args()
    base_dir = args.base_dir
    expression_file = args.expression_file or base_dir / "filtered_gene_expression_data.txt"
    signature_file = args.signature_file or base_dir / "ARCHS4_Kinases_Coexp.txt"
    out_dir = args.out_dir or base_dir / "ssGSEA_results"
    out_dir.mkdir(parents=True, exist_ok=True)

    expression_df = pd.read_csv(expression_file, sep="\t", index_col=0)
    expression_df.index = expression_df.index.map(str)

    signatures = load_signatures(signature_file)

    ssgsea_results = gp.ssgsea(
        data=expression_df,
        gene_sets=signatures,
        outdir=str(out_dir),
        sample_norm_method="rank",
        scale=False,
        min_size=args.min_size,
        max_size=args.max_size,
        permutation_num=0,
        no_plot=True,
    )

    long_report = ssgsea_results.res2d.copy()
    long_report_file = out_dir / "ssgsea_enrichment_scores_long.tsv"
    long_report.to_csv(long_report_file, sep="\t", index=False)

    required_cols = {"Name", "Term", "NES"}
    if not required_cols.issubset(long_report.columns):
        raise ValueError(
            f"Expected ssGSEA result columns {required_cols}, got {set(long_report.columns)}"
        )

    nes_matrix = long_report.pivot(index="Name", columns="Term", values="NES")
    nes_matrix = nes_matrix.reindex(index=expression_df.columns)
    nes_matrix_file = out_dir / "ssgsea_NES_matrix.tsv"
    nes_matrix.to_csv(nes_matrix_file, sep="\t")

    print(f"Scored {expression_df.shape[1]} samples against {len(signatures)} signatures")
    print(f"Wrote long ssGSEA report: {long_report_file}")
    print(f"Wrote NES matrix: {nes_matrix_file}")


if __name__ == "__main__":
    main()
